kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "serv-pipeline-test"
spec:
  source:
    git:
      uri: "https://github.com/edubois10/cicd-pipeline.git"
      ref: "main"
    sourceSecret:
      name: "basicsecret"
    contextDir: "openshift"
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: TST_TAG
          value: tst
        - name: E2E_TAG
          value: e2e
        - name: PROD_TAG
          value: prod
      jenkinsfilePath: Jenkinsfile
